# Generated by Django 5.1.2 on 2024-11-13 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0003_alter_class_time_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='time_table',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a.timetable'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a.class'),
        ),
    ]
