# Generated by Django 5.1.2 on 2024-11-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0004_alter_class_time_table_alter_lecture__class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricularactivity',
            name='image',
            field=models.ImageField(default='activities/default.jpg', upload_to='activities/'),
        ),
        migrations.AddField(
            model_name='extracurricularactivity',
            name='link',
            field=models.URLField(default='https://www.example.com'),
        ),
    ]
