# Generated by Django 5.1.2 on 2024-11-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0005_extracurricularactivity_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracurricularactivity',
            name='image',
            field=models.ImageField(default='uploads/activities/default.jpg', upload_to='uploads/activities/'),
        ),
    ]
