# Generated by Django 5.1.2 on 2024-11-16 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0006_alter_extracurricularactivity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeldLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.lecture')),
                ('students', models.ManyToManyField(to='a.student')),
            ],
        ),
    ]
