# Generated by Django 5.1.2 on 2024-11-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0007_heldlecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Event Title', max_length=256)),
                ('image', models.ImageField(default='uploads/events/default.jpg', upload_to='uploads/events/')),
                ('description', models.TextField(default='Event description')),
                ('link', models.URLField(default='https://www.example.com')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ExtraCurricularActivity',
        ),
    ]
