# Generated by Django 5.1.2 on 2024-11-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0008_event_delete_extracurricularactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCurricularActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ExtraCurricularActivities Title', max_length=256)),
                ('image', models.ImageField(default='uploads/activities/default.jpg', upload_to='uploads/activities/')),
                ('description', models.TextField(default='description')),
                ('link', models.URLField(default='https://www.example.com')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
