# Generated by Django 5.1.2 on 2024-11-19 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0009_extracurricularactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.CharField(default='Monday', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='linkedin',
            field=models.URLField(default='https://www.linkedin.com'),
        ),
        migrations.AddField(
            model_name='event',
            name='participation_registration',
            field=models.URLField(default='https://www.example.com'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration',
            field=models.URLField(default='https://www.example.com'),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='Venue', max_length=256),
        ),
    ]
