# Generated by Django 5.1.2 on 2024-11-20 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0012_block_room_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.block'),
        ),
    ]
