# Generated by Django 5.1.2 on 2024-11-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0013_alter_room_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcreservation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='pcreservation',
            name='start_time',
        ),
        migrations.AddField(
            model_name='pcreservation',
            name='slot',
            field=models.CharField(choices=[('08:30-10:00', '08:30 to 10:00'), ('10:00-11:30', '10:00 to 11:30'), ('11:30-01:00', '11:30 to 01:00'), ('01:00-02:30', '01:00 to 02:30'), ('02:30-04:00', '02:30 to 04:00'), ('04:00-05:30', '04:00 to 05:30')], default='08:00-10:00', max_length=11),
        ),
    ]
