# Generated by Django 5.1.2 on 2024-11-24 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0014_remove_pcreservation_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(default='A+', max_length=4),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='Father Name', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(default='Father Occupation', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(default='Guardian Name', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_occupation',
            field=models.CharField(default='Guardian Occupation', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='nic',
            field=models.CharField(default='00000-0000000-0', max_length=16),
        ),
    ]
