# Generated by Django 5.1.2 on 2024-11-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0015_student_blood_group_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, to='a.adacemiccalendarevent'),
        ),
    ]
