# Generated by Django 5.1.2 on 2024-11-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0016_alter_academiccalendar_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.URLField(default='https://www.nist.gov/sites/default/files/styles/2800_x_2800_limit/public/images/2018/07/10/mass_spec_cd_scan.jpg'),
        ),
        migrations.AddField(
            model_name='news',
            name='youtube_link',
            field=models.URLField(default='https://www.youtube.com'),
        ),
    ]
