# Generated by Django 5.1.2 on 2024-11-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0017_news_image_url_news_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.CharField(default='https://www.nist.gov/sites/default/files/styles/2800_x_2800_limit/public/images/2018/07/10/mass_spec_cd_scan.jpg', max_length=256),
        ),
    ]
