# Generated by Django 5.1.2 on 2024-11-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0018_remove_event_image_event_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcreservation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
