# Generated by Django 5.1.2 on 2024-11-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0019_pcreservation_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_makeup_approved',
            field=models.BooleanField(default=False),
        ),
    ]
