# Generated by Django 5.1.2 on 2024-11-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0020_lecture_is_makeup_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
