# Generated by Django 5.1.2 on 2024-11-27 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0022_remove_event_day_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcreservation',
            name='reserved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='a.student'),
        ),
    ]
