# Generated by Django 5.1.2 on 2024-11-27 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0023_pcreservation_reserved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcreservation',
            name='reserved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.student'),
        ),
    ]
