# Generated by Django 5.1.2 on 2024-12-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0025_remove_event_image_url_remove_news_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_fcm_token',
            field=models.TextField(null=True),
        ),
    ]
